#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_USER" <<-EOSQL

    -- NPM
    CREATE USER "${NPM_DB_USER}" WITH PASSWORD '${NPM_DB_PASSWORD}';
    CREATE DATABASE "${NPM_DB_NAME}" OWNER "${NPM_DB_USER}";

    -- Nextcloud
    CREATE USER "${NEXTCLOUD_DB_USER}" WITH PASSWORD '${NEXTCLOUD_DB_PASSWORD}';
    CREATE DATABASE "${NEXTCLOUD_DB_NAME}" OWNER "${NEXTCLOUD_DB_USER}";

    -- Gitea
    CREATE USER "${GITEA_DB_USER}" WITH PASSWORD '${GITEA_DB_PASSWORD}';
    CREATE DATABASE "${GITEA_DB_NAME}" OWNER "${GITEA_DB_USER}";

EOSQL
