
services:
  traefik:
    image: traefik:v3.1
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
    networks:
      homelab-network:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.khde.lan`)"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.services.traefik.loadbalancer.server.port=80"

networks:
  homelab-network:
    external: true
