
services:
  nextcloud:
    image: nextcloud:32.0.6-apache
    container_name: nextcloud 
    restart: unless-stopped
    # ports:
    #   - 8001:80
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${NEXTCLOUD_DB_NAME}
      POSTGRES_USER: ${NEXTCLOUD_DB_USER}
      POSTGRES_PASSWORD: ${NEXTCLOUD_DB_PASSWORD}
      NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
      NEXTCLOUD_TRUSTED_DOMAINS: ${NEXTCLOUD_TRUSTED_DOMAINS}
      REDIS_HOST: redis
    volumes:
      - ./nextcloud-data:/var/www/html
    networks:
      homelab-network:
    depends_on:
      - redis 

  redis:
    image: redis:8.6.0-alpine
    container_name: nextcloud-redis
    restart: unless-stopped
    volumes:
      - ./redis-data:/data
    networks:
      homelab-network:

networks:
  homelab-network:
    external: true
